name: StreetLaw CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

  lintRun:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run linting
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm run lint

  testRun:
    runs-on: ubuntu-latest
    name: Jest
    needs: [lintRun]
    steps:
      - name: Run tests
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm run test
